### ISSUE TITLE
Investigate gambit retry on Signup.postDraftReportbackSubmission error:API response is false

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/blink#57] opened 2017-05-11 13:52 UTC
CC @aaronschachter @rapala61 

This got retried 100 times, then rejected:

`at=warning application=blink env=production code=error_gambit_proxy_response_not_200_retry worker=GambitChatbotMdataProxyWorker request_id=fe887469-9c3f-403b-a520-c66a388bd5bb response_status=500 response_status_text="Internal Server Error" {"error":{"code":500,"message":"Signup.postDraftReportbackSubmission error:API response is false."}}
`

**Comment by aaronschachter** [comment] 2017-05-11 14:46
There are a [few errors in New Relic](https://rpm.newrelic.com/accounts/108038/applications/25522350/traced_errors/295d12a4-35ea-11e7-bb42-0242ac11000b_0_1109?original_error_id=295d12a4-35ea-11e7-bb42-0242ac11000b_0_1109) for `Signup.post error:API response is false.` as well.

**Comment by aaronschachter** [comment] 2017-05-18 17:34
This was likely because of the errors that are destined to fail, @sergii-tkachenko -- like  https://github.com/DoSomething/gambit/issues/881 or https://github.com/DoSomething/gambit/issues/898.  

The `Signup.post error:API response is false.` is a little bit more troublesome though.... but I haven't seen it lately. It could be caused by User account duplication, like https://github.com/DoSomething/gambit/issues/901. 

The work we're doing in #72 and https://github.com/DoSomething/gambit/issues/902 could warrant closing this issue...

**Closed** 2018-01-03 02:27 UTC
Labels: bug
